# Generated by Django 4.2.2 on 2025-03-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PostUser',
        ),
    ]
